version: '3'

services:

  app:
    build: ./app

    container_name: cloud-app

    ports:
      - "3000:3000"

    environment:
      DB_HOST: your-rds-endpoint
      DB_USER: admin
      DB_PASS: password
      DB_NAME: cloudapp

  nginx:
    image: nginx

    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app